# Generated by Django 3.0.8 on 2021-03-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Definitions_In_Circulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=512)),
                ('candidate_definition', models.CharField(max_length=4098)),
                ('times_classified', models.IntegerField(default=0)),
            ],
        ),
    ]
