# Generated by Django 3.0.8 on 2021-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_relation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=512)),
                ('time_stamp', models.TimeField(auto_now_add=True, verbose_name='Time Stamp')),
                ('main_keyword', models.CharField(max_length=512)),
                ('relationship_keyword', models.CharField(max_length=512)),
                ('relationship_is_related', models.IntegerField(default=-1)),
                ('domainnes_belongs_to_domain', models.IntegerField(default=-1)),
            ],
        ),
    ]
