# Generated by Django 3.0.8 on 2021-03-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_relation', '0002_user_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_validation',
            name='user_id',
            field=models.CharField(default='N/A', max_length=512),
            preserve_default=False,
        ),
    ]
