# Generated by Django 3.0.8 on 2021-03-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_relation', '0004_auto_20210308_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword_pages',
            name='definition',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
