# Generated by Django 3.0.8 on 2021-03-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_relation', '0005_keyword_pages_definition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword_pages',
            old_name='definition',
            new_name='wiki_definition',
        ),
    ]
