# Generated by Django 3.0.8 on 2021-03-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_relation', '0006_auto_20210322_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword_pages',
            name='google_graph_embedding',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
