# Generated by Django 3.0.8 on 2021-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_relation', '0007_keyword_pages_google_graph_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword_pages',
            name='wiki_path',
            field=models.CharField(default='', max_length=2048),
        ),
    ]
