# Generated by Django 3.0.8 on 2021-03-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_relation', '0008_keyword_pages_wiki_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Validation_Summary',
            fields=[
            ],
            options={
                'verbose_name': 'User Validation Summary',
                'verbose_name_plural': 'Users Validation Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('keyword_relation.user_validation',),
        ),
        migrations.AlterField(
            model_name='user_validation',
            name='time_stamp',
            field=models.DateField(auto_now_add=True, verbose_name='Time Stamp'),
        ),
    ]
