# Generated by Django 3.0.8 on 2021-03-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_relation', '0009_auto_20210322_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_validation',
            name='time_stamp',
            field=models.TimeField(auto_now_add=True, verbose_name='Time Stamp'),
        ),
    ]
