# Generated by Django 3.0.8 on 2021-02-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domainness_Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=512)),
                ('positive_count', models.IntegerField(default=0)),
                ('negative_match_count', models.IntegerField(default=0)),
            ],
        ),
    ]
